repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^src/
      - id: ruff-format
        files: ^src/
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.19.1
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: ["pytest"]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
  - repo: https://github.com/thoughtworks/talisman
    rev: 'v1.37.0' 
    hooks: 
      - id: talisman-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v6.0.0'
    hooks:
      - id: check-added-large-files
        